// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxBxBO5BCEKxk-FmdG8IWV4vGWrVM50k',
    appId: '1:928877243237:web:f98d2957bf118b373e0f8c',
    messagingSenderId: '928877243237',
    projectId: 'chattingapp-db098',
    authDomain: 'chattingapp-db098.firebaseapp.com',
    storageBucket: 'chattingapp-db098.firebasestorage.app',
    measurementId: 'G-F5ML4P0701',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdtuzDirvNuj3eHzM3X26ZyaKzxuqnzpQ',
    appId: '1:928877243237:android:4d936ec911fd50553e0f8c',
    messagingSenderId: '928877243237',
    projectId: 'chattingapp-db098',
    storageBucket: 'chattingapp-db098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuqOiCtjvZitd0Koy23JoIaXH881kQIi0',
    appId: '1:928877243237:ios:72f58767099d3a793e0f8c',
    messagingSenderId: '928877243237',
    projectId: 'chattingapp-db098',
    storageBucket: 'chattingapp-db098.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuqOiCtjvZitd0Koy23JoIaXH881kQIi0',
    appId: '1:928877243237:ios:72f58767099d3a793e0f8c',
    messagingSenderId: '928877243237',
    projectId: 'chattingapp-db098',
    storageBucket: 'chattingapp-db098.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxBxBO5BCEKxk-FmdG8IWV4vGWrVM50k',
    appId: '1:928877243237:web:d3863cd9d32a0de23e0f8c',
    messagingSenderId: '928877243237',
    projectId: 'chattingapp-db098',
    authDomain: 'chattingapp-db098.firebaseapp.com',
    storageBucket: 'chattingapp-db098.firebasestorage.app',
    measurementId: 'G-K4NVQD51SF',
  );

}